version: '2.1'
services:
    mysql:
      image: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: "root"
        MYSQL_PASSWORD:
      mem_limit: 1g
      #cpu-shares: 2
